{"uuid": "582a4dac-5015-4978-a10b-cea41e77af3f", "children": ["1fe0f212-461b-4070-bebc-6aa34ada8645"], "befores": [{"name": "browser", "status": "broken", "statusDetails": {"message": "urllib3.exceptions.ReadTimeoutError: HTTPConnectionPool(host='localhost', port=57680): Read timed out. (read timeout=120)\n", "trace": "  File \"D:\\REPO\\Python\\Yandex\\Sunshine\\.venv\\Lib\\site-packages\\pluggy\\_callers.py\", line 166, in _multicall\n    teardown.throw(outcome._exception)\n    ~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^\n  File \"D:\\REPO\\Python\\Yandex\\Sunshine\\.venv\\Lib\\site-packages\\_pytest\\setuponly.py\", line 36, in pytest_fixture_setup\n    return (yield)\n            ^^^^^\n  File \"D:\\REPO\\Python\\Yandex\\Sunshine\\.venv\\Lib\\site-packages\\pluggy\\_callers.py\", line 102, in _multicall\n    res = hook_impl.function(*args)\n  File \"D:\\REPO\\Python\\Yandex\\Sunshine\\.venv\\Lib\\site-packages\\_pytest\\fixtures.py\", line 1132, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"D:\\REPO\\Python\\Yandex\\Sunshine\\.venv\\Lib\\site-packages\\_pytest\\fixtures.py\", line 906, in call_fixture_func\n    fixture_result = next(generator)\n  File \"D:\\REPO\\yandex\\Diplom\\Diplom_3\\conftest.py\", line 42, in browser\n    browser.get(BASE_URL)\n    ~~~~~~~~~~~^^^^^^^^^^\n  File \"D:\\REPO\\Python\\Yandex\\Sunshine\\.venv\\Lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 393, in get\n    self.execute(Command.GET, {\"url\": url})\n    ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"D:\\REPO\\Python\\Yandex\\Sunshine\\.venv\\Lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 382, in execute\n    response = self.command_executor.execute(driver_command, params)\n  File \"D:\\REPO\\Python\\Yandex\\Sunshine\\.venv\\Lib\\site-packages\\selenium\\webdriver\\remote\\remote_connection.py\", line 404, in execute\n    return self._request(command_info[0], url, body=data)\n           ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"D:\\REPO\\Python\\Yandex\\Sunshine\\.venv\\Lib\\site-packages\\selenium\\webdriver\\remote\\remote_connection.py\", line 428, in _request\n    response = self._conn.request(method, url, body=body, headers=headers, timeout=self._client_config.timeout)\n  File \"D:\\REPO\\Python\\Yandex\\Sunshine\\.venv\\Lib\\site-packages\\urllib3\\_request_methods.py\", line 144, in request\n    return self.request_encode_body(\n           ~~~~~~~~~~~~~~~~~~~~~~~~^\n        method, url, fields=fields, headers=headers, **urlopen_kw\n        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n    )\n    ^\n  File \"D:\\REPO\\Python\\Yandex\\Sunshine\\.venv\\Lib\\site-packages\\urllib3\\_request_methods.py\", line 279, in request_encode_body\n    return self.urlopen(method, url, **extra_kw)\n           ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"D:\\REPO\\Python\\Yandex\\Sunshine\\.venv\\Lib\\site-packages\\urllib3\\poolmanager.py\", line 444, in urlopen\n    response = conn.urlopen(method, u.request_uri, **kw)\n  File \"D:\\REPO\\Python\\Yandex\\Sunshine\\.venv\\Lib\\site-packages\\urllib3\\connectionpool.py\", line 847, in urlopen\n    retries = retries.increment(\n        method, url, error=new_e, _pool=self, _stacktrace=sys.exc_info()[2]\n    )\n  File \"D:\\REPO\\Python\\Yandex\\Sunshine\\.venv\\Lib\\site-packages\\urllib3\\util\\retry.py\", line 470, in increment\n    raise reraise(type(error), error, _stacktrace)\n          ~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"D:\\REPO\\Python\\Yandex\\Sunshine\\.venv\\Lib\\site-packages\\urllib3\\util\\util.py\", line 39, in reraise\n    raise value\n  File \"D:\\REPO\\Python\\Yandex\\Sunshine\\.venv\\Lib\\site-packages\\urllib3\\connectionpool.py\", line 793, in urlopen\n    response = self._make_request(\n        conn,\n    ...<10 lines>...\n        **response_kw,\n    )\n  File \"D:\\REPO\\Python\\Yandex\\Sunshine\\.venv\\Lib\\site-packages\\urllib3\\connectionpool.py\", line 539, in _make_request\n    self._raise_timeout(err=e, url=url, timeout_value=read_timeout)\n    ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"D:\\REPO\\Python\\Yandex\\Sunshine\\.venv\\Lib\\site-packages\\urllib3\\connectionpool.py\", line 370, in _raise_timeout\n    raise ReadTimeoutError(\n        self, url, f\"Read timed out. (read timeout={timeout_value})\"\n    ) from err\n"}, "steps": [{"name": "Инициализация браузера: chrome", "status": "passed", "start": 1739895918115, "stop": 1739895920983}, {"name": "Открытие URL: https://stellarburgers.nomoreparties.site", "status": "broken", "statusDetails": {"message": "urllib3.exceptions.ReadTimeoutError: HTTPConnectionPool(host='localhost', port=57680): Read timed out. (read timeout=120)\n", "trace": "  File \"D:\\REPO\\yandex\\Diplom\\Diplom_3\\conftest.py\", line 42, in browser\n    browser.get(BASE_URL)\n    ~~~~~~~~~~~^^^^^^^^^^\n  File \"D:\\REPO\\Python\\Yandex\\Sunshine\\.venv\\Lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 393, in get\n    self.execute(Command.GET, {\"url\": url})\n    ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"D:\\REPO\\Python\\Yandex\\Sunshine\\.venv\\Lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 382, in execute\n    response = self.command_executor.execute(driver_command, params)\n  File \"D:\\REPO\\Python\\Yandex\\Sunshine\\.venv\\Lib\\site-packages\\selenium\\webdriver\\remote\\remote_connection.py\", line 404, in execute\n    return self._request(command_info[0], url, body=data)\n           ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"D:\\REPO\\Python\\Yandex\\Sunshine\\.venv\\Lib\\site-packages\\selenium\\webdriver\\remote\\remote_connection.py\", line 428, in _request\n    response = self._conn.request(method, url, body=body, headers=headers, timeout=self._client_config.timeout)\n  File \"D:\\REPO\\Python\\Yandex\\Sunshine\\.venv\\Lib\\site-packages\\urllib3\\_request_methods.py\", line 144, in request\n    return self.request_encode_body(\n           ~~~~~~~~~~~~~~~~~~~~~~~~^\n        method, url, fields=fields, headers=headers, **urlopen_kw\n        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n    )\n    ^\n  File \"D:\\REPO\\Python\\Yandex\\Sunshine\\.venv\\Lib\\site-packages\\urllib3\\_request_methods.py\", line 279, in request_encode_body\n    return self.urlopen(method, url, **extra_kw)\n           ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"D:\\REPO\\Python\\Yandex\\Sunshine\\.venv\\Lib\\site-packages\\urllib3\\poolmanager.py\", line 444, in urlopen\n    response = conn.urlopen(method, u.request_uri, **kw)\n  File \"D:\\REPO\\Python\\Yandex\\Sunshine\\.venv\\Lib\\site-packages\\urllib3\\connectionpool.py\", line 847, in urlopen\n    retries = retries.increment(\n        method, url, error=new_e, _pool=self, _stacktrace=sys.exc_info()[2]\n    )\n  File \"D:\\REPO\\Python\\Yandex\\Sunshine\\.venv\\Lib\\site-packages\\urllib3\\util\\retry.py\", line 470, in increment\n    raise reraise(type(error), error, _stacktrace)\n          ~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"D:\\REPO\\Python\\Yandex\\Sunshine\\.venv\\Lib\\site-packages\\urllib3\\util\\util.py\", line 39, in reraise\n    raise value\n  File \"D:\\REPO\\Python\\Yandex\\Sunshine\\.venv\\Lib\\site-packages\\urllib3\\connectionpool.py\", line 793, in urlopen\n    response = self._make_request(\n        conn,\n    ...<10 lines>...\n        **response_kw,\n    )\n  File \"D:\\REPO\\Python\\Yandex\\Sunshine\\.venv\\Lib\\site-packages\\urllib3\\connectionpool.py\", line 539, in _make_request\n    self._raise_timeout(err=e, url=url, timeout_value=read_timeout)\n    ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"D:\\REPO\\Python\\Yandex\\Sunshine\\.venv\\Lib\\site-packages\\urllib3\\connectionpool.py\", line 370, in _raise_timeout\n    raise ReadTimeoutError(\n        self, url, f\"Read timed out. (read timeout={timeout_value})\"\n    ) from err\n"}, "start": 1739895920983, "stop": 1739896040967}], "start": 1739895918115, "stop": 1739896040976}], "start": 1739895918115, "stop": 1739896041096}